name: Initial Pipeline
on: workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: first step
              run: echo "this is my first workflow"
            - name: checkout the repository
              uses: actions/checkout@v4
            - name: list the directory
              run: ls
#comment
    
