name: create-pipeline
on:
    workflow_dispatch
jobs:
    
    deploy_the_resources:
            runs-on: ubuntu-latest
            steps:
                - name: checkout the repository
                  uses: actions/checkout@v4
        
                - uses: azure/login@v2
                  with:
                        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
                # - name: Azure CLI script
                #   uses: azure/CLI@v1
                #   with:
                #        azcliversion: latest
                #        inlineScript: az account show

                - name: create resource group
                  run: az group create -n azuretasks -l eastus

                - name: deploy first resource
                  run:  az deployment group create -g azuretasks -f storageaccount.bicep

                - name: deploy second resource                       
                  run:  az deployment group create -g azuretasks -f ipaddress.bicep

                - name: delete the resource          
                  run: az resource delete -g azuretasks -n storage1508sn --resource-type 'Microsoft.Storage/storageAccounts'
                  
                # - name: delete the resource
                #   run: az group delete -g azuretasks --yes
    
               
                

          
                  
                    