name: Delete-pipeline
on: workflow_dispatch
jobs:
    delete_the_resource:
        runs-on: ubuntu-latest
        steps:
            - name: Azurelogin
              uses: azure/login@v2
              with:
                creds:  ${{ secrets.AZURE_CREDENTIALS }}
            - name: azureclisetup
              uses: azure/cli@v1
              with:
                azcliversion: latest
                inlinescript: az account show
            - name: delete the resource
            
              run: az resource delete -g azuretasks -n --resource-type 'Microsoft.Storage/storageAccounts'
              
